export const allBudgets = [
  {
    budget_id: 1,
    budget_type: 1,
    cat_id: 1,
    cat_name: 'Food',
    currency: 'SGD',
    default_budget: 200,
  },
  {
    budget_id: 2,
    budget_type: 1,
    cat_id: 2,
    cat_name: 'Transport',
    currency: 'SGD',
    default_budget: 100,
  },
  {
    budget_id: 3,
    budget_type: 1,
    cat_id: 3,
    cat_name: 'Entertainment',
    currency: 'SGD',
    default_budget: 150,
  },
  {
    budget_id: 4,
    budget_type: 1,
    cat_id: 4,
    cat_name: 'Rental',
    currency: 'SGD',
    default_budget: 600,
  },
  {
    budget_id: 5,
    budget_type: 2,
    cat_id: 5,
    cat_name: 'Investment',
    currency: 'SGD',
    default_budget: 1000,
  },
  {
    budget_id: 6,
    budget_type: 2,
    cat_id: 6,
    cat_name: 'Primary income',
    currency: 'SGD',
    default_budget: 3000,
  },
];
